# Generated by Django 4.1.7 on 2023-06-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='precio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id de categoria'),
        ),
    ]
