# Generated by Django 4.1.7 on 2023-06-24 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_boleta_detalle_boleta_alter_vehiculo_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_boleta',
            name='id_usuario',
        ),
    ]
