# Generated by Django 4.1.7 on 2023-06-24 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_remove_detalle_boleta_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='detalle_boleta',
            name='id_boleta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.boleta'),
            preserve_default=False,
        ),
    ]
