# Generated by Django 4.1.7 on 2023-06-24 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0009_remove_boleta_usuario_detalle_boleta_id_boleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_boleta',
            name='id_boleta',
        ),
    ]
