# Generated by Django 4.1.7 on 2023-06-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0010_remove_detalle_boleta_id_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='idBoleta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
