# Generated by Django 4.1.7 on 2023-06-25 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0013_rename_idboleta_boleta_id_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_boleta',
            name='id_boleta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.boleta'),
        ),
    ]
